version: '3.4'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    environment:
      - PLEX_CLAIM=$PLEX_CLAIM
      - ADVERTISE_IP="http://${NETWORK_IP}:32400"
      - TZ=${TIME_ZONE}
    networks:
      - webapp
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=leresolver"
      - "traefik.http.middlewares.plexHeaders.headers.contentSecurityPolicy=default-src 'self' https://*.plex.tv https://plex.tv https://*.plex.direct:32400 https://*.plex.direct:8443 wss://pubsub.plex.tv data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://plex.tv https://*.plex.tv https://www.gstatic.com"
      - "traefik.http.middlewares.plexHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.plexHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.plexHeaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.plexHeaders.headers.stsPreload=true"
      - "traefik.http.middlewares.plexHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.plexHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.plexHeaders.headers.browserXssFilter=true"
      - "traefik.http.middlewares.plexHeaders.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.plexCompress.compress=true"
      - "traefik.http.routers.plex.middlewares=plexHeaders,plexCompress"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - $STACK_DATA/plex/config:/config
      - $MEDIA_LOCATION/movies:/data/movies:ro
      - $MEDIA_LOCATION/movies2:/data/movies2:ro
      - $MEDIA_LOCATION/tv:/data/tv:ro
      - $MEDIA_LOCATION/tv-shows:/data/tv-shows:ro
      - $MEDIA_LOCATION/music:/data/music:ro
  tautulli:
    image: "linuxserver/tautulli"
    restart: unless-stopped
    container_name: "tautulli"
    networks:
      - media
    volumes:
      - "${STACK_DATA}/tautulli/config:/config"
    ports:
      - "${LOCAL_IP}:8181:8181"
    environment:
      - TZ=${TIME_ZONE}
networks:
  media:
  webapp:
    external:
      name: 'webapp'